### ISSUE TITLE
关于“未参加评估”导致实时GPA显示NaN的问题及一个暴力的解决方法

### ISSUE THREAD

**Issue by wzl-plasmid** [TimeSea05/gpa-calc-ucas#1]
之前有人提到过如果没有参加过评估的话，那么可以在GPA查询页面后面加个.json就能找到。我试了一下这个方法已经失效了，因为一门课程的成绩储存在json文件中的score属性中（不清楚“属性”一词用对没有），但是如果这门课程没参加评估的话score属性会显示null。

![gpa-calc-ucas](https://user-images.githubusercontent.com/97417831/177266672-14d6f40c-b8b3-4bc9-a70f-0ce01038c482.png)

回到标题中提出的问题，个人认为一种解决方法只能是**跳过未参加评估的学科，使之不参与GPA和加权平均分的计算**。虽然这样并不会得到准确的结果，但是也可以得到一个近似的结果，且总比实时GPA显示NaN强。同时我上学期只有形测忘了评估，本来也不影响GPA和加权平均，所以对我来说没啥问题hhh

我的解决方案如下：在原代码第40行后加一行`if (Number(scoreTable.rows[i].cells[4].innerHTML) == 0) continue;`。

![gpa-calc-ucas-2](https://user-images.githubusercontent.com/97417831/177266570-01b203d5-7572-4a22-953a-91c5c7612c4c.png)

原理：只有在未参加评估的情况下score的值是null，而null转换为Number之后会得到0。当然如果有人真的是0分的话那我暂时也没有办法。此外我的js水平也非常烂，如果安佬有什么更好的办法也可以试试，我去复习了Orz

**Comment by TimeSea05** [comment]
未显示评估的话会在表格中留有"未参加评估"的字样，这样一样能被NaN的测试给检测出来，这一行代码显得多余。
另外，在Javascript中使用`==`不是一个好的习惯，因为`==`通常伴随着强制类型转换，导致结果不可预知，出现奇怪且难以检测的bug，如果真的要改的话，可以考虑`===` 或者`Object.is()`等方法。
